### ISSUE TITLE
Make a roadmap to Version 1.0

### ISSUE THREAD

**Issue by shinshin86** [shinshin86/APWP#3]
- [ ] Create a multi post function.
- [ ] Create some "apwp" command.
  - [ ] Create "apwp" command.
  - [ ] "apwp" command have CRUD
- [ ] Create web base ui.
